name: ðŸš€ Deploy Next.js with Docker

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Repoâ€™ni checkout qilish
            -   name: Checkout code
                uses: actions/checkout@v4

            # 2. SSH agentni ishga tushirish
            -   name: Setup SSH
                uses: webfactory/ssh-agent@v0.9.0
                with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            # 3. Serverga deploy
            -   name: Deploy to Server
                run: |
                    ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
                      cd /var/www/wepos_landing

                      # Kodni yangilash
                      git reset --hard
                      git clean -fdx
                      git pull origin main

                      # Docker image build va run
                      docker-compose down
                      docker-compose up -d --build
                      docker image prune -f
                    EOF
